ALTER TABLE drafts ADD COLUMN IF NOT EXISTS tg_chat_id BIGINT;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS tg_message_id BIGINT;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
